ATOM_NAME = V O C H
DIM = 1 1 2
PRIMITIVE_AXIS = 1.0 0.0 0.0  0.0 1.0 0.0  0.0 0.0 1.0
BAND = 0.0 0.0 0.0  0.5 0.0 0.0  0.0 0.5 0.0  0.0 0.0 0.0  0.0 0.0 0.5  0.5 0.5 0.5  0.0 0.0 0.0  0.0 0.5 0.5  0.5 0.0 0.5  0.0 0.0 0.0  0.5 0.5 0.0
BAND_LABELS = $\Gamma$ X|Y $\Gamma$ Z|R $\Gamma$ T|U $\Gamma$ V
BAND_POINTS = 50
#MESH = 4 4 4
#GAMMA_CENTER = .TRUE.
FORCE_CONSTANTS = READ
#BAND_CONNECTION = .TRUE.
#GROUP_VELOCITY = .TRUE.
#DOS = .TRUE.
#DOS_RANGE = 0 80 1
#BAND = 0.0 0.0 0.0  0.0 0.5 0.0  0.5 0.5 0.0  0.0 0.0 0.0  0.5 0.5 0.5  0.0 0.5 0.0
#BAND_LABELS = $\Gamma$ X M $\Gamma$ R X
