ATOM_NAME = C H O Zn 
DIM = 1 1 1
PRIMITIVE_AXIS = 0.0 0.5 0.5  0.5 0.0 0.5  0.5 0.5 0.0   
BAND = 0.0 0.0 0.0  0.5 0.0 0.5  0.625 0.25 0.625 0.375 0.375 0.75  0.0 0.0 0.0  0.5 0.5 0.5  0.5 0.25 0.75  0.5 0.0 0.5
BAND_LABELS = $\Gamma$ X U|K $\Gamma$ L W X
BAND_POINTS = 50
#MESH = 8 8 8
#GAMMA_CENTER = .TRUE.
FORCE_CONSTANTS = READ
#BAND_CONNECTION = .TRUE.
#GROUP_VELOCITY = .TRUE.
#DOS = .TRUE.
#DOS_RANGE = 0 20 0.1
#BAND = 0.0 0.0 0.0  0.0 0.5 0.0  0.5 0.5 0.0  0.0 0.0 0.0  0.5 0.5 0.5  0.0 0.5 0.0
#BAND_LABELS = $\Gamma$ X M $\Gamma$ R X
### 0.0 0.5 0.5  0.5 0.0 0.5  0.5 0.5 0.0
